### ISSUE TITLE
model binding : 

### ISSUE THREAD

**Issue by tooy** [Erik-Huguet/Hotel_Artichaut#8]
Utiliser l'injection du model dans les paramètres des méthodes du contrôleur :
[[[cf doc](https://laravel.com/docs/9.x/routing#route-model-binding)](https://laravel.com/docs/9.x/routing#route-model-binding)](https://laravel.com/docs/9.x/routing#route-model-binding)

cf la signature des méthodes générée par 

```bash
# Shortcut to generate a model, migration, factory, seeder, policy, controller, and form requests...
php artisan make:model Flight --all
```

ou par ( [[doc](https://laravel.com/docs/9.x/controllers#resource-controllers)](https://laravel.com/docs/9.x/controllers#resource-controllers) )

```bash
php artisan make:controller PhotoController --resource
```

**Comment by Erik-Huguet** [comment]
ok
